name: Build-PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Prepare
        run: |
          mkdir -p target

      - name: Bump Version
        uses: timzu/act-build@master
        with:
          args: --version

      - name: pack
        run: |
          bash ./pack.sh
